version: '3'                                  # docker-composeの使用バージョン

services:                                     # コンテナから作られるサービス
  concourse-db:                               # コンテナの名前
    image: postgres:9.5                       # コンテナを作るためのイメージ
    environment:                              # 環境変数の設定
      POSTGRES_DB: concourse
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /database

  concourse-web:
    image: concourse/concourse:3.9.2          # 最新版(4.0.0,3.14.1)では動作しないためバージョン指定
    links: [concourse-db]                     # コンテナを他のサービスにリンク
    command: web                              # デフォルトのコマンドを上書き
    depends_on: [concourse-db]
    ports: ["8080:8080"]                      # ポートを公開（expose）。ホストとポートを指定（ホスト:コンテナ）するか、コンテナのポートのみ指定
    volumes: ["./keys/web:/concourse-keys"]   # パスをボリュームとしてマウント
    restart: unless-stopped # required so that it retries until conocurse-db comes up
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: admin
      CONCOURSE_BASIC_AUTH_PASSWORD: admin
      CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: admin
      CONCOURSE_POSTGRES_PASSWORD: admin
      CONCOURSE_POSTGRES_DATABASE: concourse

  concourse-worker:
    image: concourse/concourse:3.9.2
    privileged: true                          # コンテナに拡張権限を適用する
    links: [concourse-web]
    depends_on: [concourse-web]
    command: worker
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web
